/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaChat.presentation.chat;

import SistemaChat.logic.Message;
import SistemaChat.logic.User;
import SistemaChat.presentation.UsuarioTableModel;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.Observable;

/**
 *
 * @author adria
 */
public class View extends javax.swing.JFrame implements java.util.Observer{

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        colorPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        chatLog = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        enviarField = new javax.swing.JTextField();
        enviarButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaContactos = new javax.swing.JTable();
        buscarButton = new javax.swing.JButton();
        buscarField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        agregarField = new javax.swing.JTextField();
        agregarButton = new javax.swing.JButton();
        mensajeErrorEnvio = new javax.swing.JLabel();
        mensajeErrorUsuario = new javax.swing.JLabel();
        usernameLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        colorPanel.setBackground(new java.awt.Color(255, 204, 153));
        colorPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                colorPanelMousePressed(evt);
            }
        });

        chatLog.setEditable(false);
        chatLog.setBackground(new java.awt.Color(255, 255, 204));
        chatLog.setColumns(20);
        chatLog.setRows(5);
        jScrollPane2.setViewportView(chatLog);

        jLabel1.setFont(new java.awt.Font("Helvetica-Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Conversando con");

        usernameLabel.setFont(new java.awt.Font("Helvetica-Light", 1, 14)); // NOI18N
        usernameLabel.setText("user");

        enviarField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enviarFieldKeyPressed(evt);
            }
        });

        enviarButton.setBackground(new java.awt.Color(255, 255, 250));
        enviarButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        enviarButton.setText("Enviar");
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });

        listaContactos.setBackground(new java.awt.Color(255, 255, 153));
        listaContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Username", "Status"
            }
        ));
        listaContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaContactosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listaContactos);

        buscarButton.setBackground(new java.awt.Color(255, 255, 250));
        buscarButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        buscarField.setForeground(new java.awt.Color(204, 204, 204));
        buscarField.setText("Username...");
        buscarField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarFieldMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica-Light", 1, 14)); // NOI18N
        jLabel2.setText("Añadir contacto:");

        agregarField.setForeground(new java.awt.Color(204, 204, 204));
        agregarField.setText("Username...");
        agregarField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agregarFieldMousePressed(evt);
            }
        });

        agregarButton.setBackground(new java.awt.Color(255, 255, 250));
        agregarButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        agregarButton.setText("Añadir");
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });

        mensajeErrorEnvio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mensajeErrorEnvio.setForeground(new java.awt.Color(255, 0, 0));
        mensajeErrorEnvio.setText("detalle de envio");

        mensajeErrorUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mensajeErrorUsuario.setForeground(new java.awt.Color(255, 0, 0));

        usernameLabel1.setFont(new java.awt.Font("Helvetica-Light", 1, 14)); // NOI18N
        usernameLabel1.setText("Búsqueda de contactos");

        javax.swing.GroupLayout colorPanelLayout = new javax.swing.GroupLayout(colorPanel);
        colorPanel.setLayout(colorPanelLayout);
        colorPanelLayout.setHorizontalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorPanelLayout.createSequentialGroup()
                        .addComponent(agregarField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarButton))
                    .addGroup(colorPanelLayout.createSequentialGroup()
                        .addGroup(colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(mensajeErrorUsuario)
                            .addComponent(usernameLabel1)
                            .addGroup(colorPanelLayout.createSequentialGroup()
                                .addComponent(buscarField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarButton))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mensajeErrorEnvio)
                    .addGroup(colorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameLabel))
                    .addGroup(colorPanelLayout.createSequentialGroup()
                        .addComponent(enviarField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enviarButton))
                    .addComponent(jScrollPane2))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        colorPanelLayout.setVerticalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameLabel)
                    .addComponent(usernameLabel1))
                .addGap(4, 4, 4)
                .addGroup(colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(colorPanelLayout.createSequentialGroup()
                        .addGroup(colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(colorPanelLayout.createSequentialGroup()
                        .addGroup(colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enviarField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enviarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mensajeErrorEnvio))
                    .addGroup(colorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(mensajeErrorUsuario)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarFieldMousePressed
        agregarField.setText("");
        agregarField.setForeground(Color.BLACK);
    }//GEN-LAST:event_agregarFieldMousePressed

    private void colorPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorPanelMousePressed
        if(agregarField.getText() == "")
        {
            agregarField.setForeground(Color.GRAY);
            agregarField.setText("Username...");
        }
        if(buscarField.getText() == "")
        {
            buscarField.setForeground(Color.GRAY);
            buscarField.setText("Username...");
        }
    }//GEN-LAST:event_colorPanelMousePressed

    private void buscarFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarFieldMousePressed
        buscarField.setText("");
    }//GEN-LAST:event_buscarFieldMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.logout();
    }//GEN-LAST:event_formWindowClosing

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        Message message = new Message(model.getCurrent(), enviarField.getText(), model.getRecipient());
        controller.send(message);
        
    }//GEN-LAST:event_enviarButtonActionPerformed

    private void enviarFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enviarFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            Message message = new Message(model.getCurrent(), enviarField.getText(),model.getRecipient());
            controller.send(message);
        }
    }//GEN-LAST:event_enviarFieldKeyPressed

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        try {
            // Buscar el username en la lista de la base de datos  ----------------------------------------------------
            //si existe lo agrega a la lista de contactos
            // si no lo encuentra, no existe...
            controller.addContact(agregarField.getText());
            mensajeErrorUsuario.setText("");
            
        } catch (Exception ex) {
            mensajeErrorUsuario.setText("Contacto ya existe");
        }
        
 
        
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void listaContactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaContactosMouseClicked
        if(evt.getClickCount()==2){
            
            controller.seleccionar(listaContactos.getSelectedRow());
            usernameLabel.setText(model.getRecipient().getUsername());
        }
    }//GEN-LAST:event_listaContactosMouseClicked

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        User filtro = new User();
        filtro.setUsername(buscarField.getText());
        controller.buscar(filtro);
    }//GEN-LAST:event_buscarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JTextField agregarField;
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField buscarField;
    private javax.swing.JTextArea chatLog;
    private javax.swing.JPanel colorPanel;
    private javax.swing.JButton enviarButton;
    private javax.swing.JTextField enviarField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable listaContactos;
    private javax.swing.JLabel mensajeErrorEnvio;
    private javax.swing.JLabel mensajeErrorUsuario;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    // End of variables declaration//GEN-END:variables
    Model model;
    ControllerChat controller;

    public Model getModel() {
        return model;
    }

    public void setModel(Model model) {
        this.model = model;
        model.addObserver(this);
    }

    public ControllerChat getController() {
        return controller;
    }

    public void setController(ControllerChat controller) {
        this.controller = controller;
    }
    
    public void mensajeUsuarioNoEncontrado(String msg)
    {
        mensajeErrorUsuario.setText(msg);
    }
    
    @Override
    public void update(Observable updatedModel, Object parametros) {
        listaContactos.setModel(new UsuarioTableModel(model.getContactsList()));
        mensajeErrorUsuario.setText("");
        String msg = "";
        List<Message> messages = model.getChat().getMessageList();
        for(Message m: messages)
        {
            msg+=(m.getText()+"\n");
        }
        chatLog.setText(msg);
        enviarField.setText("");
        enviarField.requestFocus();
        this.setTitle("Usuario: "+model.getCurrent().getUsername());
    }
    
    

}
